# -*- coding: utf-8 -*-

VERSION = "0.0.4"

LANGUAGES = {
    'ru': {
        'title': f'Day R Моддинг (версия {VERSION}) - GUI',
        'choose_project': 'Выбрать папку проекта',
        'project_folder': 'Папка проекта:',
        'tools_folder': 'Папка с утилитами (tools):',
        'unpack': 'Распаковать resource.car',
        'decompile_all': 'Декомпилировать все .lu → .lua',
        'compile_all': 'Скомпилировать все .lua → .lu (НЕ ИСПОЛЬЗОВАТЬ!)',
        'pack': 'Упаковать resource.car (мод)',
        'compile_one': 'Скомпилировать один .lua (выбрать)',
        'decompile_one': 'Декомпилировать один .lu (выбрать)',
        'file_manager': 'Менеджер файлов',
        'open_mod_scripts': 'Открыть папку mod_scripts',
        'clean_project': 'Очистить проект',
        'choose_car': 'Выбрать resource.car',
        'log': 'Лог операций:',
        'clear_log': 'Очистить лог',
        'save_log': 'Сохранить логи',
        'status_ready': 'Готов',
        'status_running': 'Выполняется...',
        'err_no_project': 'Сначала выберите папку проекта!',
        'err_no_resource': 'Файл resource.car не выбран или не существует.',
        'success_unpack': 'Распаковка завершена. Оригиналы .lu в original_scripts/',
        'success_decompile': 'Декомпиляция завершена. .lua файлы в mod_scripts/',
        'success_compile': 'Компиляция завершена. .lu файлы в modded_lu/',
        'success_pack': 'Упаковка завершена. resource.car сохранён.',
        'choose_lua': 'Выберите .lua файл для компиляции',
        'choose_lu': 'Выберите .lu файл для декомпиляции',
        'file_not_found': 'Файл не найден',
        'decompile_one_done': 'Декомпиляция выполнена, исходный .lu удалён',
        'compile_one_done': 'Компиляция выполнена, создан .lu',
        'error_occurred': 'Ошибка выполнения! Смотрите лог.',
        'tools_ready': 'Инструменты готовы:',
        'clean_confirm': 'Вы уверены, что хотите удалить все рабочие папки (original_scripts, mod_scripts, modded_lu, packed_mod)?\nЭто действие необратимо!',
        'clean_success': 'Проект очищен. Осталась только папка resources с resource.car.',
        'pack_save_as': 'Сохранить resource.car как...',
        'pack_default': 'packed_mod/resource.car',
        'open_file_error': 'Не удалось открыть файл',
        'file_list_title': 'Список файлов для редактирования',
        'edit_btn': 'Открыть',
        'build_btn': 'Собрать',
        'show_hash': 'Хеш',
        'hash_title': 'SHA-1 хеш файла',
        'hash_empty': 'Файл пуст',
        'hash_error': 'Ошибка при вычислении хеша',
        'no_files': 'Нет файлов .lua в mod_scripts. Сначала выполните декомпиляцию.',
        'build_success': 'Файл успешно скомпилирован в .lu и помещён в modded_lu',
        'choose_car_title': 'Выберите resource.car',
        'use_saved_path': 'Использовать сохранённый путь?',
        'car_selected': 'Выбран resource.car:',
        'car_not_selected': 'Файл не выбран',
        'reset_scripts': 'Сбросить mod_scripts',
        'clear_modded': 'Очистить modded_lu',
        'reset_confirm': 'Это удалит папку mod_scripts и пересоздаст её из оригинальных .lu файлов. Продолжить?',
        'clear_modded_confirm': 'Это удалит все скомпилированные .lu файлы из modded_lu. Продолжить?',
        'help_btn': 'Помощь',
        'settings_btn': 'Настройки',
        'file_info': 'Инфо файлы',
        'search': 'Поиск:',
        'settings_title': 'Настройки',
        'font_label': 'Выберите шрифт:',
        'font_classic': 'Классический',
        'font_ro': 'RO.ttf (Red October)',
        'font_freemono': 'freemono.ttf',
        'font_russo': 'russo_one.ttf',
        'font_missing': 'Файл шрифта отсутствует. Поместите файл в папку font.',
        'font_folder': 'Открыть папку с шрифтами',
        'font_saved': 'Настройки сохранены. Перезапустите программу для применения шрифта.',
        'help_not_found': 'Инструкция не найдена. Проверьте файл {0} в папке resources/text/.',
        'info_not_found': 'Описание файлов не найдено. Проверьте файл {0} в папке resources/text/.',
        'log_saved': 'Лог сохранён в {0}',
        'log_empty': 'Лог пуст.',
        'install_btn': 'Установить',
        'install_success': 'Шрифт {0} установлен!\nПерезапустите программу для применения.',
        'install_fail': 'Не удалось установить шрифт:\n{0}',
        'admin_required_title': 'Недостаточно прав',
        'admin_required_message': 'Для корректной работы программы требуются права администратора.\nПерезапустить программу с правами администратора?',
        'console_title': 'Lua-консоль',
        'console_input_label': 'Введите код Lua (можно несколько строк):',
        'console_run_btn': 'Выполнить',
        'console_clear_btn': 'Очистить вывод',
        'console_ready': 'Lua-консоль готова. Введите код и нажмите \'Выполнить\' или Ctrl+Enter.\n\n',
        'console_executing': '>>> Выполнение кода:\n{0}\n',
        'console_result': 'Результат:\n{0}\n\n',
        'console_empty': 'Результат: (пусто)\n\n',
        'console_timeout': '[Timeout] Превышено время выполнения (10 сек)\n\n',
        'console_error': '>>> Ошибка: {0}\n\n',
        'editor_save': 'Сохранить',
        'editor_save_compile': 'Сохранить и скомпилировать',
        'editor_close': 'Закрыть',
        'editor_saved': 'Файл сохранён',
        'editor_compiled': 'Файл скомпилирован и сохранён в modded_lu',
        'file_manager_no_mod_scripts': 'Папка mod_scripts не найдена. Сначала выполните декомпиляцию.',
        'file_hash_label': 'Файл: {0}',
        'file_hash_value': 'SHA-1: {0}',
        'profile_manager_title': 'Управление профилями',
        'profile_list_label': 'Профили:',
        'profile_create_btn': 'Создать профиль',
        'profile_edit_btn': 'Изменить профиль',
        'profile_select_btn': 'Выбрать профиль',
        'profile_delete_btn': 'Удалить профиль',
        'profile_export_btn': 'Экспортировать',
        'profile_import_btn': 'Импортировать',
        'profile_create_title': 'Создание профиля',
        'profile_edit_title': 'Редактирование профиля',
        'profile_name_label': 'Название профиля:',
        'profile_desc_label': 'Описание:',
        'profile_path_label': 'Папка проекта:',
        'profile_save_btn': 'Сохранить',
        'profile_select_first': 'Сначала выберите профиль',
        'profile_delete_confirm': 'Удалить профиль \'{0}\' и все его файлы?',
        'profile_path_not_exists': 'Папка проекта не существует',
        'profile_exported': 'Профиль экспортирован в:\n{0}',
        'profile_imported': 'Профиль импортирован:\n{0}',
        'profile_name_required': 'Введите название профиля',
        'profile_path_required': 'Укажите существующую папку проекта',
        'profile_name_empty': 'Введите название',
        'profile_path_empty': 'Укажите существующую папку',
        'profile_imported_from': 'Импортирован из {0}',
        'check_one': 'Проверить один .lua',
        'check_all': 'Проверить все .lua',
        'check_btn': 'Проверить',
        'check_no_luacheck': 'luacheck.exe не найден! Поместите его в папку tools.',
        'check_error': 'Ошибка при проверке',
        'check_timeout': 'Проверка прервана по таймауту (30 сек)',
        'check_all_title': 'Пакетная проверка всех .lua',
        'check_all_start': '=== Пакетная проверка всех .lua ===',
        'check_all_no_files': 'Нет .lua файлов для проверки.',
        'check_all_complete': 'Пакетная проверка завершена. Найдено файлов с замечаниями: {0} из {1}',
        'check_single_start': '=== Проверка файла: {0} ===',
        'check_single_result': 'Результат проверки:\n{0}',
        'cmd_console_title': 'Консоль команд',
        'cmd_console_ready': '=== DayR Modding Tool Console ===\nВведите \'help\' для списка команд\n\n',
        'cmd_help': 'Доступные команды:',
        'cmd_unknown': 'Неизвестная команда: {0}',
        'cmd_help_hint': 'Введите \'help\' для списка доступных команд',
        'cmd_clear_done': 'Вывод очищен',
        'cmd_exit_done': 'Консоль закрыта',
        'cmd_lua_help': 'Открывает окно Lua-консоли',
        'cmd_lua_error': 'Ошибка при открытии Lua-консоли: {0}',
        # Ключи для диалога повторной декомпиляции
        'decompile_dialog_title': 'Повторная декомпиляция',
        'decompile_dialog_warning': '⚠️ Папка уже содержит файлы!',
        'decompile_dialog_folder_has': 'В папке {0} уже есть {1} файлов .lua.',
        'decompile_dialog_using_tool': 'Вы используете: {0}',
        'decompile_dialog_question': 'Что вы хотите сделать?',
        'decompile_dialog_replace': 'Заменить все',
        'decompile_dialog_replace_desc': 'Полностью удалить старые файлы и создать новые',
        'decompile_dialog_add_missing': 'Декомпилировать недостающие',
        'decompile_dialog_add_missing_desc': 'Добавить только те файлы, которых ещё нет в папке',
        'decompile_dialog_try_other': 'Попробовать другой инструмент',
        'decompile_dialog_try_other_desc': 'Только те файлы, которые не удалось обработать предыдущим инструментом',
        'decompile_dialog_cancel': 'Отмена',
        'decompile_dialog_confirm_replace': 'Все файлы в папке {0} будут удалены и созданы заново.\nПродолжить?',
    },
    'en': {
        'title': f'Day R Modding (version {VERSION}) - GUI',
        'choose_project': 'Choose Project Folder',
        'project_folder': 'Project Folder:',
        'tools_folder': 'Tools Folder:',
        'unpack': 'Unpack resource.car',
        'decompile_all': 'Decompile all .lu → .lua',
        'compile_all': 'Compile all .lua → .lu (DO NOT USE!)',
        'pack': 'Pack resource.car (mod)',
        'compile_one': 'Compile one .lua (choose)',
        'decompile_one': 'Decompile one .lu (choose)',
        'file_manager': 'File Manager',
        'open_mod_scripts': 'Open mod_scripts folder',
        'clean_project': 'Clean Project',
        'choose_car': 'Choose resource.car',
        'log': 'Operation log:',
        'clear_log': 'Clear log',
        'save_log': 'Save log',
        'status_ready': 'Ready',
        'status_running': 'Running...',
        'err_no_project': 'Please select the project folder first!',
        'err_no_resource': 'Resource.car file not selected or does not exist.',
        'success_unpack': 'Unpack complete. Original .lu files in original_scripts/',
        'success_decompile': 'Decompile complete. .lua files in mod_scripts/',
        'success_compile': 'Compile complete. .lu files in modded_lu/',
        'success_pack': 'Pack complete. resource.car saved.',
        'choose_lua': 'Choose a .lua file to compile',
        'choose_lu': 'Choose a .lu file to decompile',
        'file_not_found': 'File not found',
        'decompile_one_done': 'Decompile done, original .lu deleted',
        'compile_one_done': 'Compile done, .lu created',
        'error_occurred': 'Execution error! Check the log.',
        'tools_ready': 'Tools ready:',
        'clean_confirm': 'Are you sure you want to delete all working folders (original_scripts, mod_scripts, modded_lu, packed_mod)?\nThis action is irreversible!',
        'clean_success': 'Project cleaned. Only resources folder with resource.car remains.',
        'pack_save_as': 'Save resource.car as...',
        'pack_default': 'packed_mod/resource.car',
        'open_file_error': 'Could not open file',
        'file_list_title': 'File list for editing',
        'edit_btn': 'Open',
        'build_btn': 'Build',
        'show_hash': 'Hash',
        'hash_title': 'SHA-1 hash of file',
        'hash_empty': 'File is empty',
        'hash_error': 'Error computing hash',
        'no_files': 'No .lua files in mod_scripts. Run decompilation first.',
        'build_success': 'File successfully compiled to .lu and placed in modded_lu',
        'choose_car_title': 'Choose resource.car',
        'use_saved_path': 'Use saved path?',
        'car_selected': 'Selected resource.car:',
        'car_not_selected': 'File not selected',
        'reset_scripts': 'Reset mod_scripts',
        'clear_modded': 'Clear modded_lu',
        'reset_confirm': 'This will delete mod_scripts and recreate it from original .lu files. Continue?',
        'clear_modded_confirm': 'This will delete all compiled .lu files from modded_lu. Continue?',
        'help_btn': 'Help',
        'settings_btn': 'Settings',
        'file_info': 'File info',
        'search': 'Search:',
        'settings_title': 'Settings',
        'font_label': 'Select font:',
        'font_classic': 'Classic',
        'font_ro': 'RO.ttf (Red October)',
        'font_freemono': 'freemono.ttf',
        'font_russo': 'russo_one.ttf',
        'font_missing': 'Font file missing. Place the file in font folder.',
        'font_folder': 'Open font folder',
        'font_saved': 'Settings saved. Restart the program to apply font.',
        'help_not_found': 'Help file not found. Check {0} in resources/text/.',
        'info_not_found': 'File info not found. Check {0} in resources/text/.',
        'log_saved': 'Log saved to {0}',
        'log_empty': 'Log is empty.',
        'install_btn': 'Install',
        'install_success': 'Font {0} installed!\nRestart the program to apply.',
        'install_fail': 'Failed to install font:\n{0}',
        'admin_required_title': 'Admin rights required',
        'admin_required_message': 'Administrator rights are required for the program to work correctly.\nRestart the program with administrator rights?',
        'console_title': 'Lua Console',
        'console_input_label': 'Enter Lua code (multiple lines allowed):',
        'console_run_btn': 'Run',
        'console_clear_btn': 'Clear output',
        'console_ready': 'Lua console ready. Enter code and press \'Run\' or Ctrl+Enter.\n\n',
        'console_executing': '>>> Executing code:\n{0}\n',
        'console_result': 'Result:\n{0}\n\n',
        'console_empty': 'Result: (empty)\n\n',
        'console_timeout': '[Timeout] Execution time exceeded (10 sec)\n\n',
        'console_error': '>>> Error: {0}\n\n',
        'editor_save': 'Save',
        'editor_save_compile': 'Save and compile',
        'editor_close': 'Close',
        'editor_saved': 'File saved',
        'editor_compiled': 'File compiled and saved to modded_lu',
        'file_manager_no_mod_scripts': 'mod_scripts folder not found. Run decompilation first.',
        'file_hash_label': 'File: {0}',
        'file_hash_value': 'SHA-1: {0}',
        'profile_manager_title': 'Profile Manager',
        'profile_list_label': 'Profiles:',
        'profile_create_btn': 'Create Profile',
        'profile_edit_btn': 'Edit Profile',
        'profile_select_btn': 'Select Profile',
        'profile_delete_btn': 'Delete Profile',
        'profile_export_btn': 'Export',
        'profile_import_btn': 'Import',
        'profile_create_title': 'Create Profile',
        'profile_edit_title': 'Edit Profile',
        'profile_name_label': 'Profile Name:',
        'profile_desc_label': 'Description:',
        'profile_path_label': 'Project Folder:',
        'profile_save_btn': 'Save',
        'profile_select_first': 'Select a profile first',
        'profile_delete_confirm': 'Delete profile \'{0}\' and all its files?',
        'profile_path_not_exists': 'Project folder does not exist',
        'profile_exported': 'Profile exported to:\n{0}',
        'profile_imported': 'Profile imported:\n{0}',
        'profile_name_required': 'Enter profile name',
        'profile_path_required': 'Specify existing project folder',
        'profile_name_empty': 'Enter a name',
        'profile_path_empty': 'Specify existing folder',
        'profile_imported_from': 'Imported from {0}',
        'check_one': 'Check one .lua',
        'check_all': 'Check all .lua',
        'check_btn': 'Check',
        'check_no_luacheck': 'luacheck.exe not found! Place it in the tools folder.',
        'check_error': 'Error during check',
        'check_timeout': 'Check timed out (30 sec)',
        'check_all_title': 'Batch check all .lua',
        'check_all_start': '=== Batch check all .lua ===',
        'check_all_no_files': 'No .lua files to check.',
        'check_all_complete': 'Batch check complete. Files with issues: {0} out of {1}',
        'check_single_start': '=== Checking file: {0} ===',
        'check_single_result': 'Check result:\n{0}',
        'cmd_console_title': 'Command Console',
        'cmd_console_ready': '=== DayR Modding Tool Console ===\nType \'help\' for a list of commands\n\n',
        'cmd_help': 'Available commands:',
        'cmd_unknown': 'Unknown command: {0}',
        'cmd_help_hint': 'Type \'help\' for a list of available commands',
        'cmd_clear_done': 'Output cleared',
        'cmd_exit_done': 'Console closed',
        'cmd_lua_help': 'Opens the Lua console window',
        'cmd_lua_error': 'Error opening Lua console: {0}',
        # Keys for repeat decompilation dialog
        'decompile_dialog_title': 'Repeat decompilation',
        'decompile_dialog_warning': '⚠️ Folder already contains files!',
        'decompile_dialog_folder_has': 'Folder {0} already has {1} .lua files.',
        'decompile_dialog_using_tool': 'Using tool: {0}',
        'decompile_dialog_question': 'What do you want to do?',
        'decompile_dialog_replace': 'Replace all',
        'decompile_dialog_replace_desc': 'Delete old files and create new ones',
        'decompile_dialog_add_missing': 'Decompile missing',
        'decompile_dialog_add_missing_desc': 'Add only files that are not in the folder',
        'decompile_dialog_try_other': 'Try another tool',
        'decompile_dialog_try_other_desc': 'Only files that previous tool failed to process',
        'decompile_dialog_cancel': 'Cancel',
        'decompile_dialog_confirm_replace': 'All files in folder {0} will be deleted and recreated.\nContinue?',
    }
}